# Generated by Django 4.0.6 on 2022-07-17 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=255, null=True)),
                ('body_text', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('mod_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('user', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Info', models.TextField(blank=True, null=True)),
                ('Expense', models.TextField(blank=True, null=True)),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('Deadline', models.DateField(blank=True, null=True)),
                ('Continent', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, default='/images/university/university2.jpg', null=True, upload_to='images/university/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('Username', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('Bookmarks', models.TextField(blank=True, null=True)),
                ('Applications', models.TextField(blank=True, null=True)),
                ('profileimg', models.ImageField(blank=True, default='/images/users/profile.png', null=True, upload_to='images/users')),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
