# Generated by Django 4.0.6 on 2022-07-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_profile_bookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Bookmarks',
            field=models.TextField(blank=True, default='{"bookmarks":[]}', null=True),
        ),
    ]
